Fix build error with clang
/home/lars/dev/dev/qtquick3d/src/quick3dparticles/qquick3dparticlecustomshape.cpp:179:47:
error: implicit conversion from 'int' to 'float' changes value from 2147483647
to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
    int seed = rand->get(0, QPRand::Shape1) * INT_MAX;

Change-Id: I693c03458414f71aefaeb1ac6832a40739009446
Reviewed-by: Andy Nichols <andy.nichols@qt.io>
(cherry picked from commit 4a0ad31843b4170931abcfd4211a8abf882f8d3b)
Reviewed-by: Andreas Buhr <andreas.buhr@qt.io>