Fix compilation with QByteArrayView
From the submodule update:
  src/quick3d/qquick3deffect.cpp:834:73: error: no viable conversion
  from 'QStringBuilder<typename QConcatenable<QByteArray>::type, typename QConcatenable<QByteArray>::type>' (aka 'QStringBuilder<QByteArray, QByteArray>')
  to 'QByteArrayView'
         shaderPathKey.append(':' + QCryptographicHash::hash(vertex + fragment, QCryptographicHash::Algorithm::Sha1).toHex());

Change-Id: Ic9e0ae8ab3a315748ab75dfce30579013f557bf4
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Eirik Aavitsland <eirik.aavitsland@qt.io>
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>
(cherry picked from commit bd1007f1c0575860ec569e68637b0d0cd849b563)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>