Fix signed/unsigned comparison compilation error on 32 bit Android
Use static_cast to mute compiler warning/error on the form

    error: comparison of integers of different signs: 'quint32'
    (aka 'unsigned int') and 'qsizetype' (aka 'int')

when compiling for armeabi-v7a

Change-Id: I45e30b65237deb6b1396e4287bae6d1c752152d6
Reviewed-by: Assam Boudjelthia <assam.boudjelthia@qt.io>
(cherry picked from commit fe2dbee0d8b41274204199c81e92387a07c4f601)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>