Fix 'comparison of integers of different signs' compiler errors
Similar to this case:

/home/qt/work/qt/qtquick3d/src/runtimerender/
qssgrenderdefaultmaterialshadergenerator.cpp:2010:22: error: comparison
of integers of different signs: 'quint32' (aka 'unsigned int') and
'QVLABaseBase::size_type' (aka 'int') [-Werror,-Wsign-compare]
         if (imageIdx == cui.imageIndices.size())
             ~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.

Change-Id: Idda0841e42f9acb884c7f30c4129144527988b0e
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>
(cherry picked from commit 2938cb22ca7423f5d012cd4340427db889c6598b)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>