Fix buffer size in material shader generator
Integers can require up to 12 characters for serialization. gcc
complains:

...qssgrenderdefaultmaterialshadergenerator.cpp:820:43: error:
‘snprintf’ output may be truncated before the last format character
[-Werror=format-truncation=]
  820 |         std::snprintf(lightIdxStr, 11, "%d", lightIdx);
      |                                           ^
...qssgrenderdefaultmaterialshadergenerator.cpp:820:22: note:
‘snprintf’ output between 2 and 12 bytes into a destination of size 11
  820 |         std::snprintf(lightIdxStr, 11, "%d", lightIdx);
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make the buffer 12 characters long.

Amends commit 93ede44f636e073eaf819bd78ea130a4344944fe

Pick-to: 6.8
Change-Id: I40b72713e77d4c1689c01784620b3082957be428
Reviewed-by: Christian Strømme <christian.stromme@qt.io>
(cherry picked from commit 3fc4db53689eeb2ceabc9afe8eeb2eca4d43af87)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit f4e26899d76f9f0b7c73e6636276bf20f7df8b2d)