Include what you need (QRegularExpression)
qssgvertexpipelineimpl.cpp:131:35: error: variable has incomplete type 'QRegularExpression'

Change-Id: I24e1e28479c5d053689b2b1e075c10bae05cec3c
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>
(cherry picked from commit 1dd67c737bb1a8206b4acbea1f67044663438d7a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>