Fix warning from signed/unsigned mismatch
VC++2022 complains:

qssgrenderdefaultmaterialshadergenerator.cpp(1948):
error C2220: the following warning is treated as an error
qssgrenderdefaultmaterialshadergenerator.cpp(1948):
warning C4018: '>=': signed/unsigned mismatch

Use qsizetype consistently.

Change-Id: I99b3fe567162e83d75c263573e080bf29cffb192
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>
Reviewed-by: Inho Lee <inho.lee@qt.io>
(cherry picked from commit bb788d643000e8326c5a03ea10be94fe4acdd3cd)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>