Fix build: missing QOffscreenSurface include
qssgiblbaker.cpp:696:73: error: cannot convert ‘QOffscreenSurface*’ to ‘QSurface*’ in assignment

Change-Id: If05aeeb7176e4f13af9afffd16e711d6fd93906e
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>