QSSGLightmapBaker: fix build without QCoreApplication
Amends 095d7746b392d3770726953d3755f2b3d137155d. This fixes the build if
QT_QUICK3D_HAS_LIGHTMAPPER isn't defined.

qssglightmapbaker.cpp:125:72: error: unused parameter ‘ctx’ [-Werror=unused-parameter]

Task-number: QTBUG-139033
Change-Id: Ic362d473b80f7405e127fffd5d47dc10d5eb4beb
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>
(cherry picked from commit 573612ccac8bf0017e171d79e7d461b0038b05e4)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>