Remove loop over a hardcoded, single-element std::map
There's no need to loop if the map only has a single element. There's no
need to have a map if the element is hardcoded. There's also no need to
loop for the padding if the padding (of 0..3 bytes in size) can be
prepared at compile time too.

This was found by GCC 12 in C++20 mode printing a bogus -Wrestrict
warning in std::map, which this commit suppresses by removing the code.

In static member function ‘static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:423:21,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.tcc:532:22,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:1647:19,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:815:28,
/usr/include/c++/12/bits/char_traits.h:431:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]

Or in hex:
accessing 0x8000000000000002 or more bytes at offsets 0xc000000000000002 and [0xc000000000000001, 0x4000000000000000] may overlap up to 0x8000000000000005 bytes at offset -3

Change-Id: I7f354474adce419ca6c2fffd1748184b2b41a23e
Reviewed-by: Christian Strømme <christian.stromme@qt.io>
(cherry picked from commit 124dc1b77c0a7e0ea5ccff3bf6c3a1893693ccf5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>