Fix call to calloc() in tinyexr
developer-build with g++ 14 fails:

error: 'void* calloc(size_t, size_t)' sizes specified with 'sizeof'
in the earlier argument and not in the later argument
[-Werror=calloc-transposed-args]
 4926 |     calloc(sizeof(EXRTile), static_cast<size_t>(num_tiles)));
      |            ^~~~~~~~~~~~~~~
note: earlier argument should specify number of elements, later size
of each element

Fixes: QTBUG-125339
Change-Id: Iba159b7b62ab09ca9dab63ccfcedad684fce078f
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>
(cherry picked from commit a5f2275fbc3152110a0957774711c0b10481395e)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>