Assets: remove the reference before calling QMetaType::fromType
You're not allowed to get meta types for non-const references.

qmetatype.h:1139:29: error: static assertion failed: Meta Types cannot be non-const references or rvalue references.

Change-Id: I36b24183fbd041179f2ffffd170268b36cecfd9c
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit 901a2ae20e74263e76359edb5fce4f89b2fdb46a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>